name: dispatch-released
on:
  release:
    types: [ created ]
jobs:
  dispatch-released:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.LIS_DEPLOY_TOKEN }}
          repository: rinfex-holfer/life-is-short
          event-type: new-client-release
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

